project:
  type: book
  output-dir: docs

book:
  title: "PSYC 6380 Psychological Applications of Multivariate Analysis"
  author: "David Stanley"
  date: "2025-12-02"
  chapters:
    - index.qmd
    - workflow.qmd
    - qualtrics.qmd
    - correlation.qmd
    - multiple-regression.qmd
    - mr-sample-size.qmd
    - mmr.qmd
    - oneway-reg-anova.qmd
    - twoway-reg-anova.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    grid:
      body-width: 1000px
    theme: cosmo
    toc-depth: 5
  pdf:
    documentclass: scrreprt

editor: visual

