project:
  type: book
  output-dir: docs

book:
  title: "PSYC 6380 Psychological Applications of Multivariate Analysis"
  author: "David Stanley"
  date: "5/30/2023"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 4
  pdf:
    documentclass: scrreprt

editor: visual

